inherit_gem:
  rubocop-shopify: rubocop.yml

AllCops:
  Exclude:
    - bin/**/*
    - db/schema.rb
    - db/migrate/**/*
    - node_modules/**/*
    - tmp/**/*

Style/Encoding:
  Enabled: false

Layout/LineLength:
  Max: 120

Style/Documentation:
  Enabled: false

Metrics/CyclomaticComplexity:
  Enabled: false

Metrics/PerceivedComplexity:
  Enabled: false

Lint/MissingSuper:
  Enabled: false
