inherit_gem:
  rubocop-shopify: rubocop.yml

Style/Encoding:
  Enabled: false

Layout/LineLength:
  Max: 120

Style/Documentation:
  Enabled: false

Metrics/CyclomaticComplexity:
  Enabled: false

Metrics/PerceivedComplexity:
  Enabled: false

Style/DateTime:
  Enabled: false

AllCops:
  Exclude:
    - Rakefile
    - Gemfile
    - bin/**/*
    - config/**/*
    - db/migrate/**/*
    - db/schema.rb
    - node_modules/**/*
    - vendor/**/*
