version: "3"
services:
  web:
    build: .
    command: bash -c "rm -f tmp/pids/server.pid && bundle exec rails s -p 3000 -b '0.0.0.0'"
    stdin_open: true
    tty: true
    #env_file:
    #  - ./.env
    ports:
      - "3000:3000"
    volumes:
      - .:/app
      - tmp:/tmp
    environment:
      GOOGLE_OAUTH_REDIRECT_HOST: http://tanoshimu.aki
      MAIN_HOST: /
      REMOTE_IP: /

volumes:
  gems:
  redis:
  tmp:
