version: "3"
services:
  db:
    image: postgres
    volumes:
      - ./tmp/db:/var/lib/postgresql/data
    environment:
      POSTGRES_USER: anime
      POSTGRES_PASSWORD: isyourstoconquer

  redis:
    image: "redis:6"
    command: redis-server
    volumes:
      - "redis:/data"

  sidekiq:
    build: .
    command: bundle exec sidekiq -q active_storage_analysis -q active_storage_purge -q batch_queue -q sync -q default
    volumes:
      - .:/app
      - gems:/gems
      - tmp:/tmp
    depends_on:
      - redis
    environment:
      - REDIS_URL=redis://redis:6379
      - RAILS_LOG_TO_STDOUT=enabled
      - SYNC_CRAWLING=enabled

  web:
    build: .
    command: bash -c "rm -f tmp/pids/server.pid && bundle exec rails s -p 3000 -b '0.0.0.0'"
    stdin_open: true
    tty: true
    env_file:
      - ./.env
    ports:
      - "80:3000"
    volumes:
      - .:/app
      - /app/node_modules
      - gems:/gems
      - tmp:/tmp
    environment:
      BUNDLE_PATH: /gems
      REDIS_URL: redis://redis:6379
      DISABLE_GOOGLE_LOGIN: "1"
      GOOGLE_OAUTH_REDIRECT_HOST: http://tanoshimu.aki
    depends_on:
      - db
      - redis
      - es

  es:
    image: "docker.elastic.co/elasticsearch/elasticsearch:7.14.0"
    volumes:
      - es:/usr/share/es
    environment:
      - cluster.name=docker-cluster
      - bootstrap.memory_lock=true
      - discovery.type=single-node
      - "ES_JAVA_OPTS=-Xms512m -Xmx512m"
    ports:
      - 9200:9200
    ulimits:
      memlock:
        soft: -1
        hard: -1

volumes:
  gems:
  redis:
  tmp:
  es:
