version: '3'
services:
  db:
    image: postgres
    volumes:
      - ./tmp/db:/var/lib/postgresql/data
    environment:
      POSTGRES_USER: anime
      POSTGRES_PASSWORD: isyourstoconquer

  web:
    build: .
    command: bash -c "rm -f tmp/pids/server.pid && bundle exec rails s -p 3000 -b '0.0.0.0'"
    env_file:
      - ./.env
    ports:
      - '3000:3000'
    volumes:
      - .:/app
      - /app/node_modules
      - gems:/gems
    environment:
      BUNDLE_PATH: /gems
    depends_on:
      - db

volumes:
  gems:
