version: "3"
services:
  db:
    image: postgres
    volumes:
      - ./tmp/db:/var/lib/postgresql/data
    environment:
      POSTGRES_USER: anime
      POSTGRES_PASSWORD: isyourstoconquer
    networks:
      - bot_bot

  redis:
    image: "redis:6"
    command: redis-server
    volumes:
      - "redis:/data"
    networks:
      - bot_bot

  sidekiq:
    build: .
    command: bundle exec sidekiq -q active_storage_analysis -q active_storage_purge -q batch_queue -q sync -q default
    volumes:
      - .:/app
      - gems:/gems
      - tmp:/tmp
    depends_on:
      - redis
    environment:
      - REDIS_URL=redis://redis:6379
      - RAILS_LOG_TO_STDOUT=enabled
      - SYNC_CRAWLING=enabled
    networks:
      - bot_bot
  web:
    build: .
    command: bash -c "rm -f tmp/pids/server.pid && bundle exec rails s -p 3000 -b '0.0.0.0'"
    stdin_open: true
    tty: true
    env_file:
      - ./.env
    ports:
      - "80:3000"
    volumes:
      - .:/app
      - /app/node_modules
      - gems:/gems
      - tmp:/tmp
    environment:
      BUNDLE_PATH: /gems
      REDIS_URL: redis://redis:6379
      DISABLE_GOOGLE_LOGIN: "1"
      GOOGLE_OAUTH_REDIRECT_HOST: http://tanoshimu.aki
    networks:
      - bot_bot
    depends_on:
      - db
      - redis

networks:
  bot_bot:
    external: true

volumes:
  gems:
  redis:
  tmp:
