require_relative 'concerns/get_record'
require_relative 'concerns/identifiable'
require_relative 'concerns/resource_fetch'
require_relative 'concerns/respond_to_types'
require_relative 'concerns/translatable'
