default: &default
  adapter: sqlite3
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>
  timeout: 5000

postgres: &postgres
  adapter: postgresql
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>
  timeout: 5000

development:
  <<: *default
  database: tanoshimu_development

test:
  <<: *default
  database: tanoshimu_test

production:
  <<: *postgres
  database: tanoshimu_production
  username: anime
  password: <%= ENV["TANOSHIMU_DATABASE_PASSWORD"] %>
