# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 43d2c26fd7d5b21dcd8ace7b6dfdc73bfce973d16aea4087a4035f42a3d920558a95c4455af9fd8fed136f2de818ea4112caf8ee7ac0b326267626b6e30f64f4

test:
  secret_key_base: 8b6a71ed64de5ddfc8a09db0c044dac158742a4ce6b45f0d9e35d01908f261dc377a53e79b7632b262e44d37567d11e8d8fbae16e6466568d7c22e8ebadc6508

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
