name: Ruby

on: [push, pull_request]

jobs:
  verify:
    name: Build
    runs-on: ubuntu-latest

    services:
      postgres:
        image: postgres:11
        env:
          POSTGRES_USER: tanoshimu
          POSTGRES_DB: tanoshimu_test
          POSTGRES_PASSWORD: ""
        ports: ["5432:5432"]

    steps:
      - uses: actions/checkout@v1
      - name: Set up Ruby
        uses: actions/setup-ruby@v1
        with:
          ruby-version: 2.6.3
      - name: Set up Node
        uses: actions/setup-node@v1
        with:
          node-version: 10.13.0
      - name: Install dependencies
        run: |
          sudo apt-get update
          sudo apt-get -yqq install libpq-dev chromium-chromedriver
          sudo apt-get -yqq install libsqlite3-dev
          gem install bundler
          bundle install
          yarn install

      - name: Setup test database
        env:
          RAILS_ENV: test
          PGHOST: localhost
          PGUSER: tanoshimu
        run: |
          bin/rails db:create
          bin/rails db:migrate

      - name: Run tests
        run: bin/rails test

      - name: Coveralls GitHub Action
        uses: coverallsapp/github-action@v1.0.1
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
